
name: example-environment

dependencies:
  - python>=3.4
  - qutip
  - pip
  - scipy
  - numpy
  - matplotlib
  - sfepy
  - jupyter_contrib_nbextensions
  - nbgitpuller
  - mathics3
  - pip:
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
    - git+https://github.com/mmatera/iwolfram#egg=wolfram-kernel
